//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliFactory.WebSharper.Modernizr {
    
    
    public class Modernizr {
        

        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.input", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static object Input {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.input")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.inputtypes", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static object InputTypes {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.inputtypes")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.videoformat", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static object VideoFormat {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.videoformat")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.audioformat", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static object AudioFormat {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.audioformat")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.crosswindowmessaging", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool CrossWindowMessaging {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.crosswindowmessaging")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.draganddrop", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool DragAndDrop {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.draganddrop")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.historymanagement", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool HistoryManagement {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.historymanagement")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.hashchange", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool HashChange {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.hashchange")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.websockets", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool WebSockets {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.websockets")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.indexeddb", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Indexeddb {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.indexeddb")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.websqldatabase", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Websqldatabase {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.websqldatabase")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.smil", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Smil {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.smil")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.svgclippaths", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Svgclippaths {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.svgclippaths")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.svg", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Svg {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.svg")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.applicationcache", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool ApplicationCache {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.applicationcache")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.webworkers", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool WebWorkers {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.webworkers")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.sessionstorage", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool SessionStorage {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.sessionstorage")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.localstorage", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool LocalStorage {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.localstorage")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.geolocation", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Geolocation {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.geolocation")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.csstransitions", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Csstransitions {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.csstransitions")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.csstransforms3d", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Csstransforms3d {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.csstransforms3d")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.csstransforms", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Csstransforms {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.csstransforms")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.cssreflections", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Cssreflections {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.cssreflections")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.cssgradients", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Cssgradients {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.cssgradients")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.csscolumns", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Csscolumns {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.csscolumns")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.cssanimations", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Cssanimations {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.cssanimations")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.opacity", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Opacity {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.opacity")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.backgroundsize", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool BackgroundSize {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.backgroundsize")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.multiplebgs", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Multiplebgs {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.multiplebgs")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.boxshadow", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool BoxShadow {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.boxshadow")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.borderradius", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool BorderRadius {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.borderradius")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.borderimage", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool BorderImage {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.borderimage")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.hsla", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Hsla {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.hsla")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.rgba", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Rgba {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.rgba")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.video", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Video {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.video")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.audio", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Audio {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.audio")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.canvastext", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool CanvasText {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.canvastext")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.canvas", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Canvas {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.canvas")]
            get {
                throw new System.NotImplementedException();
            }
        }


        [IntelliFactory.WebSharper.InlineAttribute("Modernizr.fontface", IntelliFactory.WebSharper.ExprShape.PropertyGet)]
        public static bool Fontface {
            [IntelliFactory.WebSharper.InterfaceGenerator.InlineAttribute("Modernizr.fontface")]
            get {
                throw new System.NotImplementedException();
            }
        }

        
        internal Modernizr() {
        }
    }
}
